name: React app deployement

on:
  push:
    branches: [ ghpages ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
     - run: yarn
     - run: yarn build
    
  checkin:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - run: git config user.name github-actions
     - run: git config user.email github-actions@github.com
     - run: git --work-tree build add --all && git commit -m "Automatic Deploy action run by github-actions"
     - run : git push origin HEAD:gh-pages --force      
