name: React app deployement

on:
  push:
    branches: [ ghpages ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build React App
      run: yarn && yarn build
    - name: Checkin 
      run : git --work-tree build add --all && git commit -m "Automatic Deploy action run by github-actions"
    - name: Push
      run : git push origin HEAD:gh-pages --force      
