name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
#      - run: yarn
#      - run: yarn build
#      - run: git config user.name github-actions
#      - run: git config user.email github-actions@github.com
#      - run: git --work-tree build add --all && git commit -m "Automatic Deploy action run by github-actions"
#      - run : git push origin HEAD:gh-pages --force      
     - name: Pushes to another repository
       run: |
         git clone --single-branch --branch "main" "https://xrdavies:${{ secrets.PERSONAL_TOKEN }}@github.com/xrdavies/testpush.git";
         mkdir temp;
         mv .git temp/;
         cd testpush;
         git config --global user.name Frozen;
         git config --global user.email 1884084+xrdavies@users.noreply.github.com;
         cp -R ../public/* .;
         git add .;
         git status;
         git commit -m "Automatic commit";
         git status;
         git push "https://xrdavies:${{ secrets.PERSONA_TOKEN }}@github.com/xrdavies/testpush.git" --set-upstream main
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.PERSONA_TOKEN }}
#          repository: "https://github.com/xrdavies/testpush.git"
#          branch: main
#        ${{ secrets.API_TOKEN_GITHUB }}
