name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - run: yarn
     - run: yarn build
     - run: git config user.name github-actions
     - run: git config user.email github-actions@github.com
     - run: git --work-tree build add --all && git commit -m "Automatic Deploy action run by github-actions"
     - run : git push origin HEAD:gh-pages --force      
